apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-seed
  namespace: oapi
spec:
  selector:
    matchLabels:
      app: bff-seed
  replicas: 1
  template:
    metadata:
      labels:
        app: bff-seed
    spec:
      containers:
        - name: bff-seed
          image: IMAGE_PATTERN
          imagePullPolicy: Always
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "prod"
            - name: "LOGSTASH_URL"
              value: "logstash.elk.svc.cluster.local:5000"
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: 250m
            limits:
              memory: "1024Mi"
              cpu: 500m
          livenessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
      imagePullSecrets:
        - name: regcred
